.. This (-*- rst -*-) format file contains commonly used link targets
   and name substitutions.  It may be included in many files,
   therefore it should only contain link targets and name
   substitutions.  Try grepping for "^\.\. _" to find plausible
   candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   nipy, NIPY, Nipy, etc...

.. _delocate github: http://github.com/matthew-brett/delocate
.. _delocate pypi: http://pypi.python.org/pypi/delocate
.. _delocate issues: http://github.com/matthew-brett/delocate/issues
.. _delocate travis-ci: https://travis-ci.org/matthew-brett/delocate
.. _versioneer: https://github.com/warner/python-versioneer

.. vim:syntax=rst
