#!/usr/bin/env python
""" Copy, relink library dependencies for libraries in path
"""
# vim: ft=python
from __future__ import division, print_function, absolute_import

import sys
import os
from optparse import OptionParser, Option

from delocate import delocate_path, __version__

def main():
    parser = OptionParser(
        usage="%s PATH_TO_ANALYZE\n\n" % sys.argv[0] + __doc__,
        version="%prog " + __version__)
    parser.add_option(
        Option("-L", "--lib-path",
               action="store", type='string',
               help="Output path to copy library dependencies"))
    (opts, path) = parser.parse_args()
    if len(path) != 1:
        parser.print_help()
        sys.exit(1)
    if opts.lib_path is None:
        opts.lib_path = os.path.join(path[0], '.dylibs')
    delocate_path(path[0], opts.lib_path)


if __name__ == '__main__':
    main()
