#!/usr/bin/env python
""" List library dependencies for libraries in path
"""
# vim: ft=python
from __future__ import division, print_function, absolute_import

import sys
from optparse import OptionParser

from delocate import tree_libs, __version__

def main():
    parser = OptionParser(
        usage="%s PATH_TO_ANALYZE\n\n" % sys.argv[0] + __doc__,
        version="%prog " + __version__)
    (opts, path) = parser.parse_args()
    if len(path) != 1:
        parser.print_help()
        sys.exit(1)
    print('\n'.join(sorted(tree_libs(path[0]))))


if __name__ == '__main__':
    main()
