#!/usr/bin/env python
""" List library dependencies for libraries in path or wheel
"""
# vim: ft=python
from __future__ import division, print_function, absolute_import

import sys
import os
from optparse import OptionParser

from delocate import tree_libs, wheel_libs, __version__

def main():
    parser = OptionParser(
        usage="%s WHEEL_OR_PATH_TO_ANALYZE\n\n" % sys.argv[0] + __doc__,
        version="%prog " + __version__)
    (opts, paths) = parser.parse_args()
    if len(paths) < 1:
        parser.print_help()
        sys.exit(1)
    
    multi = len(paths) > 1
    for path in paths:
        if multi:
            print(path)
        if os.path.isdir(path):
            lib_dict = tree_libs(path)
        else:
            lib_dict = wheel_libs(path)
        print('\n'.join(sorted(lib_dict)))


if __name__ == '__main__':
    main()
